name: muzica_magica
description: UI demo pentru Muzica Magica (schema tip xilofon/tobe)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Styling and fonts
  google_fonts: ^6.2.1

  # Audio playback packages
  just_audio: ^0.10.5
  soundpool: ^2.4.1
  audio_session: ^0.2.2

  # Database (ORM over SQLite) and storage
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5

  # State management (optional)
  flutter_riverpod: ^3.0.0

  # Advertising and in-app purchases
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.0.8
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  crypto: ^3.0.6
  flutter_tts: ^4.2.3
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation for Drift and routing
  build_runner: ^2.6.0
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/instruments/
    - assets/images/
    - assets/packs/