name: muzica_magica
description: "Patch complet: rute, UI inspirat din designul tau, audio (web), localizari, JSON content"
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localizari
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Audio cross-platform (web OK)
  audioplayers: ^6.0.0

  # Opt-in fonts (poți scoate dacă nu le folosești)
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/content/
    - assets/images/
    - assets/audio/
    - assets/ui/